Title:hotfix:add eslint-typescript config for no-unused-var issue on ts
scaffold-eth/se-2 pull request #16
Opened 2022-10-14 06:01 UTC by Naim-Bijapure

added same fix https://github.com/scaffold-eth/se-2/pull/13 from master branch

2022-10-14 16:38 UTC, carletex requested changes

2022-10-14 16:38 UTC, carletex commented on packages/frontend/.eslintrc.json
> +    "no-unused-vars": "off",
I think we don't need this rule. Can you double check?

I removed that line, added this:

```
interface test {
  onChange?: (arg: string) => void;
}
```

And it works!

2022-10-15 08:23 UTC, Naim-Bijapure commented
@carletex  on this branch after merging master getting husky errors. 
as i can see lot of rules are failing from master due to "any" type used in many areas. 
we need to fix this type errors  on the master  after merging this branch

2022-10-17 23:15 UTC, carletex approved these changes

2022-10-17 23:16 UTC, merged