Add background to fixed footer buttons
scaffold-eth/se-2 pull request #172
Opened 2023-02-16 21:39 UTC by sverps

This adds a background to the fixed footer elements, but only on mobile. #123

2023-02-17 11:26 UTC, carletex commented
This is related to https://github.com/scaffold-eth/se-2/issues/123

I'd say: 

- Let's remove the background: Not a fan of the magic div with a magic number for the height.
- Use `md` instead of `lg`
- `mb-10` should be enough (instead of `mb-16`)

A couple of more fixes (existing errors):
- Could you vertically center the button with the theme switcher?
![image](https://user-images.githubusercontent.com/2486142/219638670-9800346e-9bdf-4a31-9f09-52f93e712953.png)

- Make the "Fork me...." to wrap.
![image](https://user-images.githubusercontent.com/2486142/219639153-d60ccefa-01dd-4fee-a00c-a2c01cee0bd9.png)

Thanks @sverps !!

2023-02-17 21:20 UTC, sverps commented
Thanks for the remarks :+1: 
I'll clean it up a bit when I get some more time.

2023-02-17 22:24 UTC, sverps commented
Removed the background:
![image](https://user-images.githubusercontent.com/15879327/219804948-c0c4ba5b-9c92-42a4-a65a-20fab9c1fde4.png)

As for the wrapping of the "Fork me", even on devices as small as 360px, it still renders decent, so not sure it really needs wrapping (and I couldn't get flex-wrap to work for some reason... :disappointed: )

2023-02-20 09:24 UTC, carletex commented on packages/nextjs/components/Footer.tsx
> +        <div className="flex items-center space-x-2 fixed z-20 h-16 bottom-0 left-4">
We shouldn't use magic numbers (like h-16, left-4)

Height should be a result of the element size + paddings. And we shouldn't move elements with "left / right" props (only `0`)

2023-02-20 09:25 UTC, carletex requested changes
left a code review comment. Thanks

2023-02-20 22:24 UTC, sverps commented
Had to put all fixed elements inside the same fixed parent (rather than positioning them separately) in order to be able to align them.

The pointer-events need to be passed through the parent container to access the footer links that are rendered at a lower zIndex.

Additionally, `mb-11` looked like a slightly better choice than `mb-10`:
![image](https://user-images.githubusercontent.com/15879327/220206956-9e7c0ce7-b478-4b7d-b019-afd2ab743b03.png)

2023-02-21 09:46 UTC, carletex commented
Great job @sverps 

Oh, since we are "squash&merging" you don't need to push force to the branch to keep the commit history clean. It will also avoid me having tu pull force / delete branch.

Thanks!

2023-02-21 09:47 UTC, merged