fixed text overflow
scaffold-eth/se-2 pull request #207
Opened 2023-02-23 14:18 UTC by KcPele

2023-02-23 14:56 UTC, sverps commented
You forgot to link back to the issue, always helpful to quickly find what a PR is fixing :)

> Fixes #205

2023-02-23 14:57 UTC, carletex commented
Also adding screenshots (before / after) is useful!

2023-02-23 15:14 UTC, carletex requested changes
Left a comment @KcPele 

Thanks

2023-02-27 11:28 UTC, KcPele commented on packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx
> +          <div className="bg-base-300 rounded-3xl break-all px-6 lg:px-8 py-4 shadow-lg shadow-base-300">
done. i have made the changes

2023-02-27 13:36 UTC, carletex commented on packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx
> +          <div className="bg-base-300 rounded-3xl break-all px-6 lg:px-8 py-4 shadow-lg shadow-base-300">
Since you added it on `DisplayVariables.tsx` you can remove it from here

2023-02-27 13:37 UTC, carletex requested changes
By mistake, you also added this to the commits. 

![image](https://user-images.githubusercontent.com/2486142/221577958-e22da026-4ca2-4d06-8fa2-3975c1630973.png)

Can you remove it?

2023-02-27 15:26 UTC, KcPele commented
> By mistake, you also added this to the commits.
> 
> ![image](https://user-images.githubusercontent.com/2486142/221577958-e22da026-4ca2-4d06-8fa2-3975c1630973.png)
> 
> Can you remove it?

please how do I remove it? it was a mistake.

2023-02-27 16:28 UTC, technophile-04 commented
> please how do I remove it? it was a mistake.
should I revert to the previous commit and make the changes again then push?

Deleted at [532172a](https://github.com/scaffold-eth/se-2/pull/207/commits/532172a3508e4326540638faf22cfcc7bcd8ee77), I think you might have faced issue while deleting because of `.git cache` 

checkout -> https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule

Also synced with `main` branch at [50e02b7](https://github.com/scaffold-eth/se-2/pull/207/commits/50e02b712def8df9936d9c8e6881547639d841a2)

Thanke @KcPele 🙌

2023-02-27 16:35 UTC, carletex commented on packages/nextjs/components/scaffold-eth/Contract/DisplayVariables.tsx
> +        <h3 className="font-medium text-lg mb-0 break-all">{functionFragment.name}</h3>
This is the h3. We wanted it on the result div

2023-02-27 16:39 UTC, merged